version: "3.9"

services:
  db:
    image: postgres:16
    container_name: mometrics-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mometrics
      POSTGRES_PASSWORD: mometrics
      POSTGRES_DB: mometrics
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
